### PR TITLE
Using non-default (22) ssh port on connections

### PR DESCRIPTION
**Pull request by GobGeeklord**
Hi there,

I'm not sure if this is a nice improvement for this project, but i couldn't find a way to specify other port than 22 on the connection element descriptor so i've implemented it.

✅ Add support to configure another port on connection element, using 'port: <portno>' descriptor.

Hope that i could be useful.

Cheers!

### CODE REVIEW

**Comment by GobGeeklord** [comment]
Hi again,

Nevermind i saw now that you already have a '**customargs**' field where you can create a custom -p entry there.

Regards

**Comment by flyingrhinonz** [comment]
Most ssh deployments use default port 22 and nccm does have the option of specifying it in the config file for exceptions. I'm thinking how many users will need non-standard ssh port by default vs feature overload.

I'll leave this item open for comments, after all - user feedback is what makes nccm so good.

**Comment by ironcrosser** [comment]
Ken, my man!
this is Tony, your childhood friend. got another way to reach you more privately? Telegram app by chance?

**Comment by flyingrhinonz** [comment]
> 

Hi Tony,

To prevent spam please email me privately to :  flyingrhino  at   orcon  dot  net  dot   nz  and tell me something that only both of us would know. This will identify both of us as genuine contacts.

**Comment by AdamOlech** [comment]
I think that specifying a different port is a fairly common use case given that a vast amount of network administration resources recommends running your Internet-facing server on a non-default port.

I'd very much appreciate this feature! Like @GobGeeklord mentioned, you can specify it in the `customargs` field but a dedicated option seems more handy. I briefly looked over the code and it looks like the changes are not drastic either.

**Comment by flyingrhinonz** [comment]
Ok, I'll implement it as a port entry as a per-server config item defaulting to port 22 such that it won't break backward compatibility.
I'm really busy in the next few weeks and it may take a while.

**Comment by AdamOlech** [comment]
@flyingrhinonz no worries, many thanks for the reply!

**Comment by flyingrhinonz** [comment]
I've made a pull req from [GobGeeklord/nccm](https://github.com/GobGeeklord/nccm) into "test" branch and implemented the code.
I'll test this new code myself for a few days before merging into master.
Meanwhile feel free to get the code from "test" branch if you want to.

BTW, I'm not seeing [GobGeeklord](https://github.com/GobGeeklord) as a contributor in the branch. Any idea how to fix this to give him credit and recognition for his code improvements?

**Pull request merged**
